version: '3'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.33
    platform: linux/amd64
    container_name: shop-database
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - "3310:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: user

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./:/var/www
    ports:
      - "8090:80"
    depends_on:
      - php

  redis:
    image: redislabs/redisearch:latest
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - '5672:5672'
      - '15672:15672'


volumes:
  redis_data:
